.github/workflows/tests.yaml
README.md
package.json

ci: add codecov reporter

---

package-lock.json
package.json

- [FIX] update es-check package

fix: update es-check package

---

.github/CODEOWNERS

ci: explicitly list code owners

---

.prettierignore

We don't need to check the formatting there because this file
shouldn't be updated manually.

fix: do not check changelog formatting

---

lib/services/core/ui/components/__tests__/buttons.test.js
lib/services/core/ui/components/buttons.js
lib/services/core/ui/messageParser/__tests__/action.js
lib/services/core/ui/messageParser/__tests__/index.test.js
lib/services/core/ui/messageParser/action.js

Unit tests

---

.husky/commit-msg
.husky/pre-commit
README.md
commitlint.config.js
lint-staged.config.js
package-lock.json
package.json

Add git hooks

---

.github/workflows/pre-release.yaml

ci: add pre-release pipeline

---

lib/services/core/ui/__tests__/register.test.js
lib/services/core/ui/messageParser/__tests__/action.test.js
lib/services/core/ui/messageParser/__tests__/form.test.js
lib/services/core/ui/messageParser/action.js
lib/services/core/ui/messageParser/form.js
lib/services/core/ui/register.js

Use UI context instead of starting flow argument to display correct forms and actions

---

LICENSE

docs(docs): adding a license file

---

README.md
jest.config.js
lib/services/core/lib/__tests__/storage.test.js
lib/services/core/lib/common/__tests__/setupRequest.test.js
lib/services/core/lib/common/setupRequest.js
lib/services/core/lib/login/__tests__/handleLogin.test.js
lib/services/core/lib/login/__tests__/oidcCallback.test.js
lib/services/core/lib/login/handleLogin.js
lib/services/core/lib/login/oidcCallback.js
lib/services/core/lib/storage.js

Linking flow

---

lib/services/core/exports/IKUICore/__tests__/render.test.js
lib/services/core/exports/IKUICore/render.js
lib/services/core/index.d.ts

Allow to specify otp token in render function

---

.github/workflows/pre-release.yaml
.github/workflows/release.yaml

ci: add release frequency tracking

---

lib/services/core/exports/IKUIUserAPI/index.js
lib/services/core/index.d.ts
lib/services/core/lib/refresh.js

Expose method refreshAccessToken so that a token can be refreshed.

feat: expose refresh access token method

---

.github/workflows/pre-release.yaml
.github/workflows/release.yaml

ci: use deployed status for cu task

---

lib/services/core/index.d.ts
lib/services/core/ui/messageParser/__tests__/index.test.js
lib/services/core/ui/messageParser/__tests__/logical.test.js
lib/services/core/ui/messageParser/__tests__/message.test.js
lib/services/core/ui/messageParser/index.js
lib/services/core/ui/messageParser/logical.js
lib/services/core/ui/messageParser/message.js

[IK-2984](https://app.clickup.com/t/36057148/IK-2984)

Render message auth node

---

lib/services/core/ui/components/buttons.js
lib/services/core/ui/components/wrap.js
lib/services/core/ui/messageParser/message.js

style: add minor styling fixes

---

.github/workflows/release.yaml

Adds metadata publisher github action.

ci: add metadata publisher github action

---

.github/workflows/release.yaml

ci: run metadata publish on release only

---

lib/services/core/lib/__tests__/storage.test.js
lib/services/core/lib/storage.js

Store thid in local storage

---

lib/services/core/locale/src/cs.json
lib/services/core/locale/src/en.json
lib/services/core/ui/components/__tests__/buttons.test.js
lib/services/core/ui/components/buttons.js

fix: remove log in with text from buttons

---

.github/ISSUE_TEMPLATE/---bug-report.md
.github/ISSUE_TEMPLATE/---feature-request.md
.github/workflows/pre-release.yaml
.github/workflows/release.yaml

ci: switch to identity workload provider

---

lib/services/core/lib/login/__tests__/oidcCallback.test.js
lib/services/core/lib/login/oidcCallback.js

Decode ans send parameters back in OIDC callback

---

lib/services/core/exports/IKUICore/__tests__/renderForm.test.js
lib/services/core/exports/IKUICore/renderForm.js
lib/services/core/index.d.ts

This function will allow you to change the DOM of the form before it's rendered.
Here's an example how to add "Terms & Conditions" content:
```ts
IKUICore.renderForm({
/* ... */
onBeforeRender: (form) => {
const termsAndConditionsEl = document.createElement('div');
termsAndConditionsEl.innerHTML = '<b>Terms & Conditions</b>';
const uiContainerEl = form.querySelector('.ui-container');
uiContainerEl?.appendChild(termsAndConditionsEl);
return form;
},
});
```

Add onBeforeRender render property

---

.github/workflows/pre-release.yaml
.github/workflows/release.yaml

Fix the permissions to allow writing to .npmrc file
Bump action versions

ci: fix the pre-release pipeline permissions

---

.github/CODEOWNERS
.github/workflows/release.yaml
CHANGELOG.md
CODING_STANDARDS.md
README.md
commitlint.config.js
lib/services/core/exports/IKUIInit/index.js
lib/services/core/lib/common/__tests__/handleForm.test.js
package-lock.json
package.json

Remove jarvis references

---

lib/services/core/lib/webauthn/__tests__/handleAssertCredentials.test.js
lib/services/core/lib/webauthn/__tests__/handleCreateCredentials.test.js
lib/services/core/lib/webauthn/__tests__/handleWebAuthn.test.js
lib/services/core/lib/webauthn/__tests__/handleWebAuthnCreateOp.test.js
lib/services/core/lib/webauthn/handleAssertCredentials.js
lib/services/core/lib/webauthn/handleCreateCredentials.js
lib/services/core/lib/webauthn/handleWebAuthn.js
lib/services/core/lib/webauthn/handleWebAuthnCreateOp.js
lib/services/core/ui/components/__tests__/dialogs.test.js
lib/services/core/ui/components/dialogs.js
lib/services/core/ui/components/inputs.js
lib/services/core/ui/components/styles/dialogs.scss
lib/services/core/ui/components/styles/styles.scss
lib/services/core/ui/messageParser/logical.js
lib/services/core/ui/messageParserNew/__tests__/index.test.js
lib/services/core/ui/messageParserNew/__tests__/webauthn.test.js
lib/services/core/ui/messageParserNew/index.js
lib/services/core/ui/messageParserNew/logical.js
lib/services/core/ui/messageParserNew/webauthn.js
lib/services/core/utils/helpers.js

How to enable WebAuthn emulator in Google Chrome (no plugin is required)
AuthFlow example
(WebAuthn Get -> WebAuthn Create -> Success route does not work)
WebAuthn configuration example

Add WebAuthn support

---

lib/services/core/lib/common/__tests__/setupRequest.test.js
lib/services/core/lib/common/setupRequest.js

Previously you weren't able to set a list of arguments together with a token (invitation token, reset password token or any other token). This fix allows you to combine all of them.

Token and arguments bug

---

package-lock.json
package.json
renovate.json

Update package versions

---

renovate.json

Set message prefix for renovate

---

.github/workflows/pre-release.yaml
.github/workflows/release.yaml
lib/services/core/__integration_tests__/renderLogin.test.js
lib/services/core/__integration_tests__/renderRegister.test.js
lib/services/core/lib/reset-password/handleSendNewPassword.js
lib/services/core/utils/__tests__/helpers.test.js
lib/services/core/utils/helpers.js
package-lock.json
package.json

The `es-check` package is failing even with trying different newer ES versions. Do we need to have it?

Remove es-check check in release

---

.github/workflows/release.yaml

Update releasing node version

---

.github/workflows/generate-docs.yaml

chore: add workflow to generate docs

---

.github/workflows/generate-docs.yaml

chore: update PAT token name in workflows

---

package-lock.json
package.json

Update package versions part 3

---

lib/services/core/ui/components/styles/buttons.scss

This PR fixes the styling of the ESSO button. 
Linked task: https://indykite.atlassian.net/browse/ENG-1855

fix: style enterprise esso button

---

lib/services/core/ui/components/styles/buttons.scss
lib/services/core/ui/components/styles/dialogs.scss
package-lock.json
package.json

fix: changed style to use wildcard
[ENG-1855](https://indykite.atlassian.net/browse/ENG-1855)
[ENG-1855]: https://indykite.atlassian.net/browse/ENG-1855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: changed style to use wildcard
